version: '3'

services:
  db:
    image: mysql
    container_name: db_my_custom_library
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_my_custom_library
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - dev
    environment:
      PMA_HOST: db
  
  www:
    build: docker
    container_name: my_custom_library
    restart: always
    ports:
    - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: