vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        book_image:
            uri_prefix: /images/book_image
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
