vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        book_image:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        auteur_photo:
            uri_prefix: /images/auteur
            upload_destination: '%kernel.project_dir%/public/images/auteur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer